In [1]:
import pip

def import_or_install(package):
    try:
        __import__(package)
    except ImportError:
        pip.main(['install', package])

import_or_install("numpy")

import numpy as np

twoDList = [[2,3,55,63],
            [4,53,44,21]]

twoDArray = np.array(twoDList) #list to array


In [16]:
import pip

def import_or_install(package):
    try:
        __import__(package)
    except ImportError:
        pip.main(['install', package])

import_or_install("numpy")

import numpy as np

np.zeros(3)

np.zeros([3,3])
np.linspace(10,100,5)

np.ones(4)

np.ones((4,4),dtype="int32") #4x4 array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [21]:
import pip

def import_or_install(package):
    try:
        __import__(package)
    except ImportError:
        pip.main(['install', package])

import_or_install("numpy")

import numpy as np

np.random.rand()

sampleArray = np.arange(25) #sort
print(sampleArray) 

sampleArray.shape

sample2dArray = sampleArray.reshape(5,5) #convert into 2d 5x5
print(sample2dArray)

sample2dArray.max()

sample2dArray = sample2dArray + 50 #add to array
print(sample2dArray)

sample2dArray.argmax()

np.max(sample2dArray)

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])
array3 = np.array([0,0,0,0,0])

sumOfArrays = array1 + array2

print(sumOfArrays)

subOfArrays = array1 - array2

print(subOfArrays)

divBy0 = array3/array1
print(divBy0)
# div0By = array1/array3
# print(div0By)

sampleArray[:-1]

sampleArray[0:10] = 10

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]]
[ 2  4  6  8 10]
[0 0 0 0 0]
[0. 0. 0. 0. 0.]


In [1]:
import pip

def import_or_install(package):
    try:
        __import__(package)
    except ImportError:
        pip.main(['install', package])

import_or_install("numpy")

import numpy as np

array1 = np.array([3,4,5])
array2 = np.array([6,3,8])
array3 = np.array([0,0,0])

sumOfArrays = array1 + array2

print(sumOfArrays)

subOfArrays = array1 - array2

print(subOfArrays)

divBy0 = array3/array1
print(divBy0)
# div0By = array1/array3
# print(div0By)

divBy6 = array2/6
print(divBy6)

mulBy4 = array2*4
print(mulBy4)

array4 = array1*array2
print(array4)

# subtraction divison numpy series dataframe multiplication (with int with array)

[ 9  7 13]
[-3  1 -3]
[0. 0. 0.]
[1.         0.5        1.33333333]
[24 12 32]
[18 12 40]
